# frozen_string_literal: true

# Shared analysis thresholds for analyze_subvariants*.rb scripts.

MINIMUM_PROFITFACTOR = 2.5
CHECK_MINIMUM_TRADERATE_ENABLED = false
CHECK_MINIMUM_TRADERATE_VALUE = 0.04
CHECK_MINIMUM_TRADERATEWEEKLY_ENABLED = true
CHECK_MINIMUM_TRADERATEWEEKLY_VALUE = 0.20
MAXIMUM_PROFITFACTOR = 9999999999999999999999999.9

MAX_COMBINATION_SIZE = 4

GROUPING_SAMPLEDATES_MAX = 50

MERGE_SAME_RESULTS = true
